# Generated by Django 2.0.3 on 2018-03-27 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20180227_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='date',
            new_name='DATE',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='tmax',
            new_name='TMAX',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='tmin',
            new_name='TMIN',
        ),
    ]
